AWSTemplateFormatVersion: 2010-09-09
Description: Demo for cloudformation-managed infra (s3 direct uploads)
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins: 
              - "*"
            AllowedMethods: 
              - POST
              - GET
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            AllowedHeaders: 
              - "*"
